#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by arch/i386/Makefile
 *
 */

#define SIGCONTEXT_eax 44 /* offsetof(struct sigcontext, eax) */
#define SIGCONTEXT_ebx 32 /* offsetof(struct sigcontext, ebx) */
#define SIGCONTEXT_ecx 40 /* offsetof(struct sigcontext, ecx) */
#define SIGCONTEXT_edx 36 /* offsetof(struct sigcontext, edx) */
#define SIGCONTEXT_esi 20 /* offsetof(struct sigcontext, esi) */
#define SIGCONTEXT_edi 16 /* offsetof(struct sigcontext, edi) */
#define SIGCONTEXT_ebp 24 /* offsetof(struct sigcontext, ebp) */
#define SIGCONTEXT_esp 28 /* offsetof(struct sigcontext, esp) */
#define SIGCONTEXT_eip 56 /* offsetof(struct sigcontext, eip) */

#define CPUINFO_x86 0 /* offsetof(struct cpuinfo_x86, x86) */
#define CPUINFO_x86_vendor 1 /* offsetof(struct cpuinfo_x86, x86_vendor) */
#define CPUINFO_x86_model 2 /* offsetof(struct cpuinfo_x86, x86_model) */
#define CPUINFO_x86_mask 3 /* offsetof(struct cpuinfo_x86, x86_mask) */
#define CPUINFO_hard_math 6 /* offsetof(struct cpuinfo_x86, hard_math) */
#define CPUINFO_cpuid_level 8 /* offsetof(struct cpuinfo_x86, cpuid_level) */
#define CPUINFO_x86_capability 12 /* offsetof(struct cpuinfo_x86, x86_capability) */
#define CPUINFO_x86_vendor_id 40 /* offsetof(struct cpuinfo_x86, x86_vendor_id) */

#define TI_task 0 /* offsetof(struct thread_info, task) */
#define TI_exec_domain 4 /* offsetof(struct thread_info, exec_domain) */
#define TI_flags 8 /* offsetof(struct thread_info, flags) */
#define TI_status 12 /* offsetof(struct thread_info, status) */
#define TI_cpu 16 /* offsetof(struct thread_info, cpu) */
#define TI_preempt_count 20 /* offsetof(struct thread_info, preempt_count) */
#define TI_addr_limit 24 /* offsetof(struct thread_info, addr_limit) */
#define TI_restart_block 28 /* offsetof(struct thread_info, restart_block) */

#define EXEC_DOMAIN_handler 4 /* offsetof(struct exec_domain, handler) */
#define RT_SIGFRAME_sigcontext 164 /* offsetof(struct rt_sigframe, uc.uc_mcontext) */
#define TSS_sysenter_esp0 -8700 /* offsetof(struct tss_struct, esp0) - sizeof(struct tss_struct) */
#define PAGE_SIZE_asm 4096 /* PAGE_SIZE */
#define VSYSCALL_BASE -8192 /* __fix_to_virt(FIX_VSYSCALL) */

#endif
